#!/bin/bash

[ "$1" == "--help" ] && echo "Usage: aex # starts single-process Apache"  \
                     && exit

source /etc/apache2/envvars
source /root/.rc

/usr/sbin/apache2 -X -d /etc/apache2
