#!/bin/bash

. $csc/scripts/cs-common

function usage() {
  echo "dgt -d <dataset-dir> -n <predictor-count> [ (-1 <standalone-mode> -s <php-src-dir> ) | ( -p <server-port> ) ]"
  echo "    [ -t train/test ]"
  echo "    # predictor-count: number of predictors to report (-1 for all)"
}

check_help $1 usage

append_classpath "CROWD_SAFE_COMMON_DIR"
append_classpath "SCRIPT_SAFE_MERGE_DIR"

main_class="edu.uci.eecs.scriptsafe.analysis.dictionary.DictionaryTest"

#echo "java -cp $cp $main_class $@"
java -Xms512M -Xmx2048M -cp $cp $main_class $@
