#!/bin/bash

. $csc/scripts/cs-common

function usage() {
  echo "fst -d <dataset-dir> -s <php-src-dir> -k <cross-validation-file> -i <config-file>"
}

check_help $1 usage

append_classpath "CROWD_SAFE_COMMON_DIR"
append_classpath "SCRIPT_SAFE_MERGE_DIR"

main_class="edu.uci.eecs.scriptsafe.feature.FeatureService"

#echo "java -cp $cp $main_class $@"
java -Xms512M -Xmx2048M -cp $cp $main_class -t $@
