#!/bin/bash

. $csc/scripts/cs-common

function usage() {
  echo "kg -k <group-size> -d <dataset-dir> -o <output-file>"
}

check_help $1 usage

append_classpath "CROWD_SAFE_COMMON_DIR"
append_classpath "SCRIPT_SAFE_MERGE_DIR"

main_class="edu.uci.eecs.scriptsafe.feature.CrossValidationSetGenerator"

#echo "java -cp $cp $main_class $@"
java -Xms512M -Xmx2048M -cp $cp $main_class $@
