#!/bin/bash

[ -z "$PHP_CFI" ] && echo "This build script requires environment variable 'PHP_CFI' to be set."

cd $PHP_CFI/opmon
[ ! -e "./configure" ] && $PHP_HOME/scripts/phpize
[ ! -e "./Makefile" ] && ./current-config
make install

imagick="/hd/lib/imagick/imagick/modules/imagick.so"

if [ -e "$imagick" ]
then
  cp -u $imagick modules
else
  echo "Not install the imagick module (not found)"
fi
